// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB2jb9Q3dFV5g9luhFEw7twLt63UvdoxMc',
    appId: '1:202805568635:android:8c38b9c8b67b21918b2ede',
    messagingSenderId: '202805568635',
    projectId: 'firbase-tutorail',
    storageBucket: 'firbase-tutorail.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDJObsbnaEpAPEmd2lEH-LVWfL7KkGq0nI',
    appId: '1:202805568635:ios:df97dcc9364a544b8b2ede',
    messagingSenderId: '202805568635',
    projectId: 'firbase-tutorail',
    storageBucket: 'firbase-tutorail.appspot.com',
    androidClientId: '202805568635-vmeb5brtohmuck6hteuu22oahi2fnvpv.apps.googleusercontent.com',
    iosClientId: '202805568635-fm3mu32rr3a5k9ve7ihr0l4iahvdfn93.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebasePushNotification',
  );
}
